module-template: ! 'module MODULE_NAME where

'
extensions:
  BangPatterns: true
environment: ghc-7.4.2-stable-13.09
cabal-file: project.cabal
hidden-packages: ''
version: 1
extra-packages: ! 'Hackage: repa


'
ghc-args: []
excluded-modules: []
